### ISSUE TITLE
Deploy issue to heroku

### ISSUE THREAD

**Issue by kyleevert** [CityOfZion/coz-slack-ico-management-platform#1]
Hi @totalvm 
Thank you for sharing this code first.
I have some issue with deploying this code to the heroku.
I have configured the heroku vars like your instructions.
![image](https://user-images.githubusercontent.com/9217217/32794388-00f03004-c969-11e7-9634-a54dafa80ad4.png)
![image](https://user-images.githubusercontent.com/9217217/32794399-0afc5154-c969-11e7-90e8-1e58f5ed6746.png)

And the build log is like this:

-----> Node.js app detected
-----> Clearing cache dir.
-----> Installing meteor
Downloading Meteor distribution

Meteor 1.6 has been installed in your home directory (~/.meteor).

Now you need to do one of the following:

  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/app/tmp/cache/meteor/.meteor/packages/meteor-tool/1.6.0/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor

Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
-----> Target Meteor version: Meteor 1.6-beta.27
-----> Checking if this meteor version supports --server-only
-----> Using node: v8.5.0
----->    and npm: 5.4.1
added 273 packages in 23.761s
-----> Building Meteor app with ROOT_URL: https://dreamten-slack.herokuapp.com/ 
-----> Moving built slug to /tmp/build_60f76a4cfc75b05e650192a6be606668/.meteor/heroku_build/app
-----> Installing npm production dependencies on built slug

> fibers@2.0.0 install /tmp/build_60f76a4cfc75b05e650192a6be606668/.meteor/heroku_build/app/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /tmp/build_60f76a4cfc75b05e650192a6be606668/.meteor/heroku_build/app/programs/server
> node npm-rebuild.js

{
  "meteor-dev-bundle": "0.0.0",
  "npm": "5.4.1",
  "ares": "1.10.1-DEV",
  "cldr": "31.0.1",
  "http_parser": "2.7.0",
  "icu": "59.1",
  "modules": "57",
  "nghttp2": "1.25.0",
  "node": "8.5.0",
  "openssl": "1.0.2l",
  "tz": "2017b",
  "unicode": "9.0",
  "uv": "1.14.1",
  "v8": "6.0.287.53",
  "zlib": "1.2.11"
}
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

added 124 packages in 8.161s
-----> Adding PATH environment
-----> Running extras
-----> Adding profile script to resolve MONGO_URL from mongolab addon
-----> Adding profile script to resolve ROOT_URL from heroku app name
-----> Clearing cache dir.
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web

-----> Compressing...
       Done: 95.8M
-----> Launching...
       Released v14
       https://dreamten-slack.herokuapp.com/ deployed to Heroku

The heroku app was deployed as you see, but I can see some issues on logs.
`  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/app/tmp/cache/meteor/.meteor/packages/meteor-tool/1.6.0/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor`

And when I go to the site(https://dreamten-slack.herokuapp.com/), nothing happens(got js error) when I click the buttons.
![image](https://user-images.githubusercontent.com/9217217/32794647-b521c68c-c969-11e7-993f-ba5b8d28576e.png)
 I am not familiar with meteor/nodejs, so I don't know how to fix this issue.
I am really appreciate if you tell me how to fix this issue.

Best,
Kyle

**Comment by totalvm** [comment]
@calemyers723 
Looking at the error it seems like the service isn't configured, what this means is that the entry from the database is missing:

```
db.meteor_accounts_loginServiceConfiguration.insert({
	"service" : "slack",
	"clientId" : "your_slack_client_id",
	"secret" : "your_slack_secret",
	"loginStyle" : "redirect"
})
```

**Comment by kyleevert** [comment]
@totalvm 
Thank you for your quick help.
After adding that data, it seems like working.
I will contact you if I have got any questions.

Best regards,
Kyle

**Comment by kyleevert** [comment]
Hi @totalvm 
https://dreamten-slack.herokuapp.com

When I try to login, I have got the error.
![image](https://user-images.githubusercontent.com/9217217/32844046-a8fea31c-ca21-11e7-8dc9-5ab305780411.png)
Actually the slack app was installed by owner.
Could you please let me know the reason?

Best,
Kyle

**Comment by kyleevert** [comment]
@totalvm 
After installed app was approved by owner, I have got another error.
`Oops, looks like there's no route on the client or the server for url: "https://dreamten-slack.herokuapp.com/%20/_oauth/slack?code=130079851954.272812420818.5a2df090b1f018174c06a97cde66c22eb9c4dac7d19ebd1bd3541ce9bf7f07b7&state=eyJsb2dpblN0eWxlIjoicmVkaXJlY3QiLCJjcmVkZW50aWFsVG9rZW4iOiJha0dqeGQyUnFGRm1nd05KdyIsImlzQ29yZG92YSI6ZmFsc2UsInJlZGlyZWN0VXJsIjoiaHR0cHM6Ly9kcmVhbXRlbi1zbGFjay5oZXJva3VhcHAuY29tLyJ9."`

![image](https://user-images.githubusercontent.com/9217217/32845013-04850882-ca24-11e7-9a42-17aef31b2723.png)

The captured video url:
https://www.screencast.com/t/yKcw4KmnVEZ

Please give me your advise.

Many thanks,
Kyle

**Comment by totalvm** [comment]
@calemyers723 I think it would be best if we have contact via a chat program so it will be easier to help you.

For now I can see one of the following things going wrong:
- Slack oauth URL is wrong in your slack apps
- The person logging in has no admin rights

**Comment by kyleevert** [comment]
@totalvm 
Can I have your skype id?

**Comment by totalvm** [comment]
@calemyers723 mdewal
