### ISSUE TITLE
Invites broken

### ISSUE THREAD

**Issue by chatch** [CityOfZion/coz-slack-ico-management-platform#2]
Can't get an invite at: https://slack-helper.cityofzion.io/invite/T656BRXQ8

The Recaptcha redirects back to itself forever.

Some users discussed this problem here too : https://www.reddit.com/r/NEO/comments/7ecxgd/how_to_join_neo_slack/

**Comment by totalvm** [comment]
Yes Slack has disabled every way for us to invite, none of the methods work anymore

**Comment by chatch** [comment]
oh i see .. is there anyway you can help me sign up at all?  I'd like to join if possible.

**Comment by totalvm** [comment]
unfortunately no, there is currently no way to generate invites. We are looking to switching to a different platform.

**Comment by chatch** [comment]
alright. i'll look out for it. :+1:   maybe update or shutdown the invite screen in the meantime. it's a bit confusing. others are having the same problem too.

**Comment by totalvm** [comment]
I will push an update which shows a message

**Comment by chatch** [comment]
replaced by discord: https://discordapp.com/invite/R8v48YA
